#端口号配置
server:
  port: 8080


spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:}
    username: ${MYSQL_USERNAME:}
    password: ${MYSQL_PASSWORD:}
  #spring自带的检测文件大小限制
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 2MB
  #redis配置
  data:
    redis:
      host: ${REDIS_HOST:}
      port: 6379

#mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full   #开启嵌套映射
  mapper-locations: classpath*:/mapper/**/*.xml

#阿里云OSS参数
aliyun:
  oss:
    endpoint: ${ALIYUN_OSS_ENDPOINT:}
    bucketName: ${ALIYUN_OSS_BUCKET:}

#关闭异常处理器响应体通用重写，绕过报错代码
springdoc:
  override-with-generic-response: false

#调用deepseek对话补全参数
deepseek:
  api:
    apikey: ${DEEPSEEK_API_KEY:}
    base-uri: https://api.deepseek.com/chat/completions
    model: deepseek-v4-flash
    max-tokens: 2048
    temperature: 0.3

# JWT登录配置
jwt:
  secret: ${JWT_SECRET:}
  expire-minutes: 120
