#端口号配置
server:
  port: 8080


spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/ai_jump_test"
    username: root
    password: 5201314
  #spring自带的检测文件大小限制
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 2MB
  #redis配置
  data:
    redis:
      host: 192.168.158.128
      port: 6379

#mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full   #开启嵌套映射
  mapper-locations: classpath*:/mapper/**/*.xml

#阿里云OSS参数
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: ai-jumptest

#关闭异常处理器响应体通用重写，绕过报错代码
springdoc:
  override-with-generic-response: false